name: PR Debug

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Workflow triggered"
